[package]
name = "rust-lesson-1"
version = "0.1.0"
edition = "2021"
[workspace]
members = ["lesson1", "lesson3"]
[dependencies]
snafu = "0.8.3"
[profile.dev1]
inherits = "dev"
opt-level = 1
[profile.dev2]
inherits = "dev"
opt-level = 2
